name: 'Build AppImage'
description: 'Build an AppImage using appimage-builder'
branding:
  icon: 'package'
  color: 'green'
inputs:
  recipe:
    description: 'appimage-builder recipe file'
    required: true
    default: 'AppImageBuilder.yml'
  args:
    description: 'appimage-builder arguments'
    required: false
    default: '--skip-test'
runs:
  using: 'docker'
  image: docker://appimagecrafters/appimage-builder:1.1.0
  args:
    - appimage-builder
    - '--recipe=${{ inputs.recipe }}' 
    - '${{ inputs.args }}'
